# Generated by Django 5.1.4 on 2024-12-30 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='home.area'),
        ),
        migrations.AlterField(
            model_name='services',
            name='service_type',
            field=models.CharField(max_length=50),
        ),
    ]
