# Generated by Django 5.1.4 on 2024-12-17 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='user',
        ),
    ]
