# Generated by Django 5.1.4 on 2024-12-17 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_serviceproviderprofile_area_and_more'),
        ('home', '0002_remove_services_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='accounts.serviceproviderprofile'),
            preserve_default=False,
        ),
    ]
