# Generated by Django 5.1.4 on 2024-12-20 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_area_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='street',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
