# Generated by Django 5.1.4 on 2024-12-20 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_area_street'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='street',
        ),
    ]
