# Generated by Django 5.1.4 on 2024-12-20 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_area_street'),
    ]

    operations = [
        migrations.CreateModel(
            name='Streets',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, null=True, unique=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streets', to='home.area')),
            ],
        ),
    ]
