# Generated by Django 5.1.4 on 2024-12-20 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_streets'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Streets',
        ),
    ]
