# Generated by Django 5.1.4 on 2024-12-20 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_delete_streets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicecategory',
            old_name='service_category_name',
            new_name='name',
        ),
    ]
