# Generated by Django 5.1.4 on 2024-12-20 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_rename_service_category_name_servicecategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecategory',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
