# Generated by Django 5.1.4 on 2024-12-17 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('home', '0002_remove_services_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='providers_in_area', to='home.area'),
        ),
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='providers_in_city', to='home.city'),
            preserve_default=False,
        ),
    ]
