# Generated by Django 5.1.4 on 2024-12-17 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_serviceproviderprofile_area_and_more'),
        ('home', '0004_alter_services_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_service_provider',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='service_description',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='providers_in_service_description', to='home.services'),
            preserve_default=False,
        ),
    ]
