# Generated by Django 5.1.4 on 2024-12-19 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customertype_emailqueue'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='customer_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
