# Generated by Django 5.1.4 on 2024-12-19 07:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customuser_customer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Phone number must contain only numbers.', regex='^\\d+$')]),
        ),
    ]
