# Generated by Django 5.1.4 on 2024-12-19 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_customuser_phone'),
        ('home', '0004_alter_services_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceproviderprofile',
            name='area',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='providers_in_area', to='home.area'),
        ),
        migrations.AlterField(
            model_name='serviceproviderprofile',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='providers_in_city', to='home.city'),
        ),
    ]
