# Generated by Django 5.1.4 on 2024-12-19 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_serviceproviderprofile_area_and_more'),
        ('home', '0004_alter_services_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceproviderprofile',
            name='area',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='providers_in_area', to='home.area'),
        ),
    ]
