# Generated by Django 5.1.4 on 2024-12-19 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_serviceproviderprofile_area_and_more'),
        ('home', '0007_alter_area_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceproviderprofile',
            name='area',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='providers_in_area', to='home.area'),
        ),
        migrations.AlterField(
            model_name='serviceproviderprofile',
            name='city',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='providers_in_city', to='home.city'),
        ),
    ]
