# Generated by Django 5.1.4 on 2024-12-19 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_serviceproviderprofile_area_and_more'),
        ('home', '0007_alter_area_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceproviderprofile',
            name='service_description',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='providers_in_service_description', to='home.services'),
        ),
    ]
