# Generated by Django 5.1.4 on 2024-12-20 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_serviceproviderprofile_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
