# Generated by Django 5.1.4 on 2024-12-20 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_serviceproviderprofile_street'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceproviderprofile',
            name='service_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
