# Generated by Django 5.1.4 on 2024-12-20 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_serviceproviderprofile_service_description'),
        ('home', '0011_delete_streets'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='service_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='home.servicecategory'),
        ),
    ]
