# Generated by Django 5.1.4 on 2024-12-20 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_serviceproviderprofile_service_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceproviderprofile',
            name='service_category',
        ),
    ]
