# Generated by Django 5.1.4 on 2024-12-20 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_remove_serviceproviderprofile_service_category'),
        ('home', '0014_alter_servicecategory_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='service_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='providers_in_category', to='home.servicecategory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='serviceproviderprofile',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='providers_in_area', to='home.area'),
        ),
        migrations.AlterField(
            model_name='serviceproviderprofile',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='providers_in_city', to='home.city'),
        ),
    ]
