# Generated by Django 5.1.4 on 2024-12-20 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_serviceproviderprofile_service_category_and_more'),
        ('home', '0014_alter_servicecategory_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceproviderprofile',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='providers_in_area', to='home.area'),
        ),
        migrations.AlterField(
            model_name='serviceproviderprofile',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='providers_in_city', to='home.city'),
        ),
        migrations.AlterField(
            model_name='serviceproviderprofile',
            name='service_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='providers_in_category', to='home.servicecategory'),
        ),
    ]
