# Generated by Django 5.1.4 on 2024-12-20 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_serviceproviderprofile_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to='accounts.serviceproviderprofile'),
        ),
    ]
