# Generated by Django 5.1.4 on 2024-12-20 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_customerprofile_provider'),
        ('home', '0014_alter_servicecategory_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_profiles', to='home.servicecategory'),
        ),
    ]
